<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_RedDiverter" Id="{d6963702-b12f-4902-8e4d-5e93d3250f33}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RedDiverter EXTENDS FB_BaseDiverter
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Sort" Id="{834ee0ba-bb18-4f09-9be0-ec3069d19092}">
      <Declaration><![CDATA[METHOD PUBLIC Sort
VAR_INPUT
    color : E_Color;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF color = E_Color.RED THEN
    Start();
END_IF]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>